import mongoose from "mongoose";

// One reconciliation finding. Always produced deterministically by the
// reconciliation engine (services/reconciliationEngine.js) - never by the LLM.
const discrepancySchema = new mongoose.Schema(
  {
    user: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true, index: true },
    batchId: { type: String, required: true, index: true },

    type: {
      type: String,
      required: true,
      enum: [
        "MISSING_PAYMENT",
        "ORPHAN_PAYMENT",
        "AMOUNT_MISMATCH",
        "DUPLICATE_CHARGE",
        "REFUND_SHORTFALL",
        "PAYMENT_NOT_SETTLED",
        "CANCELLED_BUT_CHARGED",
        "CURRENCY_MISMATCH",
        "DUPLICATE_ORDER_RECORD",
      ],
    },

    severity: { type: String, enum: ["high", "medium", "low"], required: true },

    orderRef: { type: String }, // normalized order id this finding is about
    orders: [{ type: mongoose.Schema.Types.ObjectId, ref: "Order" }],
    payments: [{ type: mongoose.Schema.Types.ObjectId, ref: "Payment" }],

    amountAtRisk: { type: Number, required: true, default: 0 },
    currency: { type: String, default: "USD" },

    // Deterministic, human-readable description generated by the engine (not the LLM).
    summary: { type: String, required: true },

    // Structured facts the LLM (or the UI) can use without re-deriving them.
    details: { type: mongoose.Schema.Types.Mixed },

    status: { type: String, enum: ["open", "resolved", "ignored"], default: "open" },
  },
  { timestamps: true }
);

discrepancySchema.index({ user: 1, batchId: 1, type: 1 });

export default mongoose.model("Discrepancy", discrepancySchema);
